// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bus-geo-service/internal/biz"
	"bus-geo-service/internal/conf"
	"bus-geo-service/internal/data"
	"bus-geo-service/internal/server"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer, logger)
	client := data.NewRedisClient(confData)
	gocentClient := data.NewCent(confData)
	dataData, cleanup, err := data.NewData(confData, logger, client, gocentClient)
	if err != nil {
		return nil, nil, err
	}
	busRepo := data.NewBusRepo(dataData)
	busUseCase := biz.NewBusUseCase(busRepo)
	goCloak := data.NewKeycloak(confData)
	keycloakAPI := data.NewKeyCloakAPI(confData, goCloak, logger)
	httpServer := server.NewHTTPServer(confServer, busUseCase, keycloakAPI, logger)
	customHTTP := server.NewCustomHttp(confServer, busUseCase, logger)
	app := newApp(logger, grpcServer, httpServer, customHTTP)
	return app, func() {
		cleanup()
	}, nil
}
